version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the docker image...
      - docker build -t 0margrj-apps .
      - docker tag 0margrj-apps:latest 019562922826.dkr.ecr.eu-west-1.amazonaws.com/0margrj-apps:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 019562922826.dkr.ecr.eu-west-1.amazonaws.com/0margrj-apps:latest